# Description of this example is provided in NTRU.md

from ntru import *

#Bob
print ("Bob Will Generate his Public Key using Parameters")
print ("N=7,p=29 and q=491531")
Bob=Ntru(11,3,31)
f=[1,1,-1,0,-1,1]
g=[-1,0,1,1,0,0,-1]
print ("f(x)= ",f)
print ("g(x)= ",g)
Bob.genPublicKey(f,g)
pub_key=Bob.getPublicKey()
print ("Public Key Generated by Bob: ",pub_key)
print ("-------------------------------------------------")
#Alice
alice=Ntru(11,3,31)
alice.setPublicKey(pub_key)
msg=[1,0,1,0,1,1,1]
print ("Alice's Original Message   : ",msg)
ranPol=[-1,-1,1,1]
print ("Alice's Random Polynomial  : ",ranPol)
encrypt_msg=Alice.encrypt(msg,ranPol)
print ("Encrypted Message          : ", encrypt_msg)
print ("-------------------------------------------------")
#BOB
print ("Bob decrypts message sent to him")
print ("Decrypted Message          : ", Bob.decrypt(encrypt_msg))